---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rswat.maker

An R package for building QSWAT+ inputs and creating SWAT+ projects. This manages model creation. See also the related project [`rswat`](https://github.com/deankoch/rswat), which handles outputs and more.

<!-- badges: start -->
<!-- badges: end -->


## Installation

You can install the development version of `rswat.maker` like so:

``` r
devtools::install_github('deankoch/rswat.maker')
```

## Background

SWAT+ is a comprehensive watershed-level water movement simulator, with a large user base in
the hydrology research community. Read more about the simulator at its Texas A&M project
[homepage](https://swat.tamu.edu/software/plus/).

SWAT+ uses a very data-intensive modelling strategy, where
the number of unknowns can be quite large (tens- to hundreds of thousands of parameters). 
However, it provides software tools with graphical interfaces (GUIs) to assist users
in setting reasonable fill-in values for these parameters. The tools are: QSWAT+ (a QGIS
plugin), and SWAT+ Editor (standalone Windows software).

I come from an R-based statistical analysis background, so my first thought after following
this workflow was to find an alternative to the GUIs. This is because in order to properly
test SWAT+/QSWAT+ (or a modification of it), we would need to run this workflow repeatedly -
many times, with different inputs - and this is best done programmatically, in a language
like R or Python.

This package streamlines the creation of SWAT+ models, by collecting data inputs in R and
managing the batch execution of QSWAT+ and SWAT+ Editor via shell scripts.


## Purpose

SWAT+ has a limited but growing presence in the R data analysis world. The purpose of
this package is to further bridge these two worlds by creating a new workflow for building
SWAT+ modelling that can be completed, start-to-finish, without leaving the R environment.
This workflow is:

1. reproducible
2. programmable
3. extensible

Best of all, it makes a huge number of R-based statistical analysis and GIS tools
accessible to a SWAT+ modeler. Like QGIS, R (and its CRAN packages) are open-source, free
to use, and well-documented. We believe there is a great potential to improve SWAT+ by putting
it under the microscope in R, where it can be confronted it with new methodologies and ideas 
that may deviate from the standard QSWAT+ workflow.


## Datasets

A number of different earth sciences datasets are needed to initialize a SWAT+ model:

* landscape feature polygons - including an AOI and the water bodies in it
* digital elevation model raster (DEM)
* land use raster (and lookup table)
* soils classification raster (and lookup table)
* stream flow time series

`rswat.maker` takes an outlet location of interest, finds the corresponding
watershed area, then downloads and processes the required datasets from public sources.
It produces a set of output files ready for QSWAT+, and retains copies of the source
datasets for later use. 

In batch mode, the workflow then proceeds to call `shell` to run QSWAT+, followed by
SWAT+ Editor. The result is a set of SWAT+ configuration files, ready execution and training. 
Users can also run QSWAT+ manually if they wish, using the files generated by this package
as inputs.

`rswat.maker` is primarily a data-retrieval package, so it remains useful to
hydrologists and earth systems scientists who aren't interested in the SWAT+ simulator. With
the exception of `write_wx`, there is no dependency on `rswat`, and users can run most of the
workflow in (all but the last three steps) without ever installing SWAT+ or its helper software.


## Areas of interest

`rswat.maker` relies (in its very first step) on geometries downloaded from NHDplus, and
these are currently only available in the continental USA.  

Our watershed of interest is the Upper Yellowstone, so most of the testing in `rswat.maker`
has focused on areas upstream of Carter's Bridge, Montana (near Livingston). This includes
Paradise Valley and most of Yellowstone National Park. In the vignette we look at one its
tributaries, the Lamar River.


`rswat.maker` is largely based on code in the [URYW_data repository](https://github.com/deankoch/UYRW_data), which has been greatly simplified
so that it can be maintained as a self-contained R package. 


## Motivation

The purpose of `rswat.maker` is to automate and document ETL for the datasets required by
QSWAT+ when creating any new SWAT+ model. This is part of a larger effort to create
reproducible workflows for SWAT+ simulations in research

The package helps us manage a freshwater forecasting system for the Upper Yellowstone
River (UYR) watershed based around SWAT+ simulations.


## Development to-do list

* CRAN checks
* Lamar River vignette

