## code to prepare `swatplus_soils` dataset 
## template generated by running `usethis::use_data_raw('swatplus_soils')`

## dependencies: `RSQLite`, `DBI`, `dplyr`, `usethis` packages and one input file (see below)
## inputs: change path below to the correct path to "swatplus_soils.sqlite" on your local machine!
## output: in your package data directory: /data/swatplus_soils


## constants

# SQLite database from SWAT+ Editor or https://bitbucket.org/swatplus/swatplus.editor/downloads/
swat_soil_path = file.path('C:/SWAT/SWATPlus/Databases', 'swatplus_soils.sqlite')

# load the relevant tables from the SWAT+ database and join them
swat_soil_sql = RSQLite::SQLite() |> DBI::dbConnect(swat_soil_path)
my_join = \(nm) swat_soil_sql |> DBI::dbReadTable(nm) |> dplyr::mutate(survey=nm)
swatplus_soils_df = do.call(rbind, lapply(c('ssurgo', 'statsgo'), my_join)) |> dplyr::tibble()
swat_soil_sql |> DBI::dbDisconnect()

# save as package data
swatplus_soils = swatplus_soils[['muid']]
usethis::use_data(swatplus_soils, overwrite = TRUE)
