## code to prepare `us_states` dataset 
## template generated by running `usethis::use_data_raw('us_states')`

## dependencies: `usethis` `maps`, `sf` packages
## output: in your package data directory: /data/us_states.rda


library(sf)
library(usmap)

# the projection used by us_map and the output projection (WGS84)
crs_in = usmap::usmap_crs() |> sf::st_crs()
crs_out = sf::st_crs(4326)

# get a list of coordinates for USA state polygons
states_df = usmap::us_map()
states_list = states_df |> split(states_df[['abbr']])

# loop over states
states_result = vector(mode='list', length=length(states_list))
for(i in seq_along(states_result)) {
  
  # get the full name and abbreviation
  state_attr = states_list[[i]][c('abbr', 'full')] |> apply(2, unique, simplify=FALSE)
  
  # split the coordinates into pieces, make polygons, then join together again
  state_poly = states_list[[i]] |> 
    split(states_list[[i]][['piece']]) |> 
    lapply(\(sdf) {
      
      sdf[c('x', 'y')] |> 
        as.matrix() |> 
        sf::st_multipoint() |> 
        list() |> 
        sf::st_polygon()
      
    }) |> sf::st_multipolygon() |> sf::st_sfc(crs=crs_in) 
  
  # bundle as sf object and copy to storage
  states_result[[i]] = sf::st_sf(data.frame(state_attr), geometry=state_poly)
}

# concatenate as a single sf data frame with MULTIPOLYGON in desired projection
us_states = do.call(rbind, states_result) |> sf::st_transform(crs_out)

# save as package data
usethis::use_data(us_states, overwrite=TRUE)
