## code to prepare `usgs_lookup` dataset
## template generated by running `usethis::use_data_raw('usgs_lookup')`

## dependencies: `usethis` packages
## output: in your package data directory: /data/usgs_lookup.rda


## constants

# HTML query for USGS Water Data codes from waterdata.usgs.gov (downloads a .txt file)
water_query_url = 'https://help.waterdata.usgs.gov/code/parameter_cd_query?fmt=rdb&group_cd=%'


## helpers

# downloads and returns a parameter code name/definition table from USGS
get_usgs_lookup = function(water_query_url) {

  # fetch the table and pipe to R data frame
  usgs_txt = water_query_url |> read.delim(comment.char='#')

  # return a cleaned up version
  usgs_txt |>
    tail(-1) |>
    dplyr::filter(!is.na(parm_cd))
}


## run

# call the helper to get STATSGO https download URLs
usgs_lookup = water_query_url |> get_usgs_lookup()

# save as package data
usethis::use_data(usgs_lookup, overwrite = TRUE)
